config/routes.rb
Marcasite::Engine.routes.draw do
  resources :themes
  resources :pages
  resources :articles do
    resources :comments
  end
  root to: "articles#index"

  scope :admin do
    get '/', to: 'admin#index', as: :admin
    get 'general', to: 'admin#general', as: :general_admin
    get 'posts', to: 'admin#posts', as: :post_admin
    get 'pages', to: 'admin#pages', as: :page_admin
    get 'analytics',  to: 'admin#analytics', as: :analytics_admin
    get 'plugins', to: 'admin#plugins', as: :plugins_admin
    get 'themes', to: 'admin#themes', as: :themes_admin
  end
end

app/models/marcasite/application_record.rb
module Marcasite
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/marcasite/article.rb
module Marcasite
  class Article < ApplicationRecord
    has_many :comments
    extend FriendlyId
    friendly_id :title, use: :slugged
  end
end

app/models/marcasite/comment.rb
module Marcasite
  class Comment < ApplicationRecord
    belongs_to :article
  end
end

app/models/marcasite/page.rb
module Marcasite
  class Page < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
  end
end

app/models/marcasite/theme.rb
module Marcasite
  class Theme < ApplicationRecord
  end
end

app/controllers/marcasite/admin_controller.rb
module Marcasite
  class AdminController < ApplicationController
    layout 'marcasite/admin'
    def index
      @panel = view_context.render(partial: 'general')
    end
    def general
      @panel = view_context.render(partial: 'general')
      render 'index'
    end
    def posts
      @articles = Article.all
      @panel = view_context.render(partial: 'posts')
      render 'index'
    end
    def pages
      @pages = Page.all
      @panel = view_context.render(partial: 'pages')
      render 'index'
    end
    def analytics
      @panel = view_context.render(partial: 'analytics')
      render 'index'
    end
    def plugins
      @panel = view_context.render(partial: 'plugins')
      render 'index'
    end
    def themes
      @themes = Theme.all
      @panel = view_context.render(partial: 'themes')
      render 'index'
    end
  end
end

app/controllers/marcasite/application_controller.rb
module Marcasite
  class ApplicationController < ActionController::Base
    $theme = Theme.all.first rescue nil
  end
end

app/controllers/marcasite/articles_controller.rb
module Marcasite
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy ]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: "Article was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: "Article was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy!
      redirect_to articles_url, notice: "Article was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def article_params
        params.require(:article).permit(:title, :text)
      end
  end
end

app/controllers/marcasite/comments_controller.rb
module Marcasite
  class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      flash[:notice] = "Comment has been created!"
      redirect_to articles_path
    end
    
    private
      def comment_params
        params.require(:comment).permit(:text)
      end
  end
end

app/controllers/marcasite/pages_controller.rb
module Marcasite
  class PagesController < ApplicationController
    before_action :set_page, only: %i[ show edit update destroy ]

    # GET /pages
    def index
      @pages = Page.all
    end

    # GET /pages/1
    def show
    end

    # GET /pages/new
    def new
      @page = Page.new
    end

    # GET /pages/1/edit
    def edit
    end

    # POST /pages
    def create
      @page = Page.new(page_params)

      if @page.save
        redirect_to @page, notice: "Page was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /pages/1
    def update
      if @page.update(page_params)
        redirect_to @page, notice: "Page was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /pages/1
    def destroy
      @page.destroy!
      redirect_to pages_url, notice: "Page was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_page
        @page = Page.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def page_params
        params.require(:page).permit(:title, :text, :slug)
      end
  end
end

app/controllers/marcasite/themes_controller.rb
module Marcasite
  class ThemesController < ApplicationController
    before_action :set_theme, only: %i[ show edit update destroy ]

    # GET /themes
    def index
      @themes = Theme.all
    end

    # GET /themes/1
    def show
    end

    # GET /themes/new
    def new
      @theme = Theme.new
    end

    # GET /themes/1/edit
    def edit
    end

    # POST /themes
    def create
      @theme = Theme.new(theme_params)

      if @theme.save
        redirect_to @theme, notice: "Theme was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /themes/1
    def update
      if @theme.update(theme_params)
        redirect_to @theme, notice: "Theme was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /themes/1
    def destroy
      @theme.destroy!
      redirect_to themes_url, notice: "Theme was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_theme
        @theme = Theme.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def theme_params
        params.require(:theme).permit(:name, :description, :css, :modifiable)
      end
  end
end

app/helpers/marcasite/themes_helper.rb
module Marcasite
  module ThemesHelper
  end
end

app/views/marcasite/themes/_form.html.erb
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :css, style: "display: block" %>
    <%= form.text_area :css %>
  </div>

  <div>
    <%= form.label :modifiable, style: "display: block" %>
    <%= form.check_box :modifiable %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/marcasite/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <p>
    <strong>Name:</strong>
    <%= theme.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= theme.description %>
  </p>

  <p>
    <strong>Css:</strong>
    <%= theme.css %>
  </p>

  <p>
    <strong>Modifiable:</strong>
    <%= theme.modifiable %>
  </p>

</div>

app/views/marcasite/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/marcasite/themes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Themes</h1>

<div id="themes">
  <% @themes.each do |theme| %>
    <%= render theme %>
    <p>
      <%= link_to "Show this theme", theme %>
    </p>
  <% end %>
</div>

<%= link_to "New theme", new_theme_path %>

app/views/marcasite/themes/new.html.erb
<h1>New theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/marcasite/themes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @theme %>

<div>
  <%= link_to "Edit this theme", edit_theme_path(@theme) %> |
  <%= link_to "Back to themes", themes_path %>

  <%= button_to "Destroy this theme", @theme, method: :delete %>
</div>