config/routes.rb
Marcasite::Engine.routes.draw do
  resources :themes
  resources :pages
  resources :articles do
    resources :comments
  end
  root to: "articles#index"

  scope :admin do
    get '/', to: 'admin#index', as: :admin
    get 'general', to: 'admin#general', as: :general_admin
    get 'posts', to: 'admin#posts', as: :post_admin
    get 'pages', to: 'admin#pages', as: :page_admin
    get 'analytics',  to: 'admin#analytics', as: :analytics_admin
    get 'plugins', to: 'admin#plugins', as: :plugins_admin
    get 'themes', to: 'admin#themes', as: :themes_admin
  end
end

app/models/marcasite/application_record.rb
module Marcasite
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/marcasite/article.rb
module Marcasite
  class Article < ApplicationRecord
    has_many :comments
    extend FriendlyId
    friendly_id :title, use: :slugged
  end
end

app/models/marcasite/comment.rb
module Marcasite
  class Comment < ApplicationRecord
    belongs_to :article
  end
end

app/models/marcasite/page.rb
module Marcasite
  class Page < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
  end
end

app/models/marcasite/theme.rb
module Marcasite
  class Theme < ApplicationRecord
  end
end

app/controllers/marcasite/admin_controller.rb
module Marcasite
  class AdminController < ApplicationController
    layout 'marcasite/admin'
    def index
      @panel = view_context.render(partial: 'general')
    end
    def general
      @panel = view_context.render(partial: 'general')
      render 'index'
    end
    def posts
      @articles = Article.all
      @panel = view_context.render(partial: 'posts')
      render 'index'
    end
    def pages
      @pages = Page.all
      @panel = view_context.render(partial: 'pages')
      render 'index'
    end
    def analytics
      @panel = view_context.render(partial: 'analytics')
      render 'index'
    end
    def plugins
      @panel = view_context.render(partial: 'plugins')
      render 'index'
    end
    def themes
      @themes = Theme.all
      @panel = view_context.render(partial: 'themes')
      render 'index'
    end
  end
end

app/controllers/marcasite/application_controller.rb
module Marcasite
  class ApplicationController < ActionController::Base
    $theme = Theme.all.first rescue nil
  end
end

app/controllers/marcasite/articles_controller.rb
module Marcasite
  class ArticlesController < ApplicationController
    before_action :set_article, only: %i[ show edit update destroy ]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: "Article was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: "Article was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy!
      redirect_to articles_url, notice: "Article was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def article_params
        params.require(:article).permit(:title, :text)
      end
  end
end

app/controllers/marcasite/comments_controller.rb
module Marcasite
  class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      flash[:notice] = "Comment has been created!"
      redirect_to articles_path
    end
    
    private
      def comment_params
        params.require(:comment).permit(:text)
      end
  end
end

app/controllers/marcasite/pages_controller.rb
module Marcasite
  class PagesController < ApplicationController
    before_action :set_page, only: %i[ show edit update destroy ]

    # GET /pages
    def index
      @pages = Page.all
    end

    # GET /pages/1
    def show
    end

    # GET /pages/new
    def new
      @page = Page.new
    end

    # GET /pages/1/edit
    def edit
    end

    # POST /pages
    def create
      @page = Page.new(page_params)

      if @page.save
        redirect_to @page, notice: "Page was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /pages/1
    def update
      if @page.update(page_params)
        redirect_to @page, notice: "Page was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /pages/1
    def destroy
      @page.destroy!
      redirect_to pages_url, notice: "Page was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_page
        @page = Page.friendly.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def page_params
        params.require(:page).permit(:title, :text, :slug)
      end
  end
end

app/controllers/marcasite/themes_controller.rb
module Marcasite
  class ThemesController < ApplicationController
    before_action :set_theme, only: %i[ show edit update destroy ]

    # GET /themes
    def index
      @themes = Theme.all
    end

    # GET /themes/1
    def show
    end

    # GET /themes/new
    def new
      @theme = Theme.new
    end

    # GET /themes/1/edit
    def edit
    end

    # POST /themes
    def create
      @theme = Theme.new(theme_params)

      if @theme.save
        redirect_to @theme, notice: "Theme was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /themes/1
    def update
      if @theme.update(theme_params)
        redirect_to @theme, notice: "Theme was successfully updated.", status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /themes/1
    def destroy
      @theme.destroy!
      redirect_to themes_url, notice: "Theme was successfully destroyed.", status: :see_other
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_theme
        @theme = Theme.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def theme_params
        params.require(:theme).permit(:name, :description, :css, :modifiable)
      end
  end
end

app/helpers/marcasite/themes_helper.rb
module Marcasite
  module ThemesHelper
  end
end

app/views/marcasite/admin/_analytics.html.erb
<h4>Analytics</h4>

app/views/marcasite/admin/_general.html.erb
<h4>General</h4>

app/views/marcasite/admin/_pages.html.erb
<h4>Pages</h4>
<%= link_to "New Page", new_page_path %>
  <% @pages.each do |page| %>
            <h2><%= link_to page.title, page %></h2>
<% end %>

app/views/marcasite/admin/_plugins.html.erb
<h4>Plugins</h4>

app/views/marcasite/admin/_posts.html.erb
<h4>Posts</h4>
  <%= link_to "New article", new_article_path %>
  <% @articles.each do |article| %>
            <h2><%= link_to article.title, article %></h2>
<% end %>

app/views/marcasite/admin/_sidenav.html.erb
<div class="sidebar close">
    <div class="logo-details">
      <i class='bx bx-book'></i>
      <span class="logo_name">Marcasite</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href="#">
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><%= link_to "General", general_admin_path, class: "link_name" %></li>
        </ul>
      </li>
      <li>
        <div class="iocn-link">
          <a href="#">
            <i class='bx bx-collection' ></i>
            <span class="link_name">Category</span>
          </a>
          <i class='bx bxs-chevron-down arrow' ></i>
        </div>
        <ul class="sub-menu">
          <li><a class="link_name" href="#">Category</a></li>
          <li><a href="#">HTML & CSS</a></li>
          <li><a href="#">JavaScript</a></li>
          <li><a href="#">PHP & MySQL</a></li>
        </ul>
      </li>
      <li>
        <div class="iocn-link">
          <a href="#">
            <i class='bx bx-book-alt' ></i>
            <span class="link_name">Posts</span>
          </a>
          <i class='bx bxs-chevron-down arrow' ></i>
        </div>
        <ul class="sub-menu">
          <%= link_to "Posts", post_admin_path, class: "link_name" %>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class='bx bx-book-open' ></i>
          <span class="link_name">Pages</span>
        </a>
        <ul class="sub-menu blank">
          <%= link_to "Pages", page_admin_path, class: "link_name" %>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class='bx bx-line-chart' ></i>
          <span class="link_name">Analytics</span>
        </a>
        <ul class="sub-menu blank">
           <%= link_to "Analytics", analytics_admin_path, class: "link_name" %>
        </ul>
      </li>
      <li>
          <a href="#">
            <i class='bx bx-plug' ></i>
            <span class="link_name">Plugins</span>
          </a>
          <i class='bx bxs-chevron-down arrow' ></i>
         <ul class="sub-menu blank">
           <%= link_to "Plugins", plugins_admin_path, class: "link_name" %>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class='bx bx-compass' ></i>
          <span class="link_name">Themes</span>
        </a>
        <ul class="sub-menu blank">
         <%= link_to "Themes", themes_admin_path, class: "link_name" %>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class='bx bx-history'></i>
          <span class="link_name">History</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">History</a></li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class='bx bx-cog' ></i>
          <span class="link_name">Setting</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Setting</a></li>
        </ul>
      </li>
      <li>
    <div class="profile-details">
      <div class="profile-content">
        <!--<img src="image/profile.jpg" alt="profileImg">-->
      </div>
      <div class="name-job">
        <div class="profile_name">Prem Shahi</div>
        <div class="job">Web Desginer</div>
      </div>
      <i class='bx bx-log-out' ></i>
    </div>
  </li>
</ul>
  </div>
  
  <script>
  let arrow = document.querySelectorAll(".arrow");
  for (var i = 0; i < arrow.length; i++) {
    arrow[i].addEventListener("click", (e)=>{
   let arrowParent = e.target.parentElement.parentElement;//selecting main parent of arrow
   arrowParent.classList.toggle("showMenu");
    });
  }
  let sidebar = document.querySelector(".sidebar");
  let sidebarBtn = document.querySelector(".bx-menu");
  console.log(sidebarBtn);
  sidebarBtn.addEventListener("click", ()=>{
    sidebar.classList.toggle("close");
  });
  </script>

app/views/marcasite/admin/_themes.html.erb
<h4>Themes</h4>  

<%= link_to "New theme", new_theme_path %>
  <% @themes.each do |theme| %>
            <h2><%= link_to theme.name, theme %></h2>
<% end %>

app/views/marcasite/admin/index.html.erb
<%= render partial: "sidenav" %>
<section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
      <span class="text">Administration</span>
      
      
    </div>
    <div style="padding-left: 20px" >
      <%= @panel %>
    </div>
  </section>
  
  <div class="one">
  </div>
  